# Generated by Django 4.1.3 on 2024-05-16 16:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Целевая группа',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.datetime(2024, 5, 16, 19, 40, 45, 333188), verbose_name='Создан в')),
                ('min_price', models.FloatField(verbose_name='Минимальная цена')),
                ('max_price', models.FloatField(verbose_name='Максимальная цена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос на формирование рекомендаций',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koef', models.FloatField(verbose_name='Коэфициент корреляции')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.request')),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.targetgroup')),
            ],
            options={
                'verbose_name': 'Анализ',
            },
        ),
    ]
